### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by mulikaminker** [nmaro/staart#1]

**Comment by nickredmark** [comment]
Hi there, if you mean registration with facebook or google, yes, that part isn't implemented yet (as is written in the readme: https://github.com/nmaro/staart).
Does registration with email/password work for you?

**Comment by mulikaminker** [comment]
@nmaro, thanks for the quick response. 
I tried to register in your demo app and it does nothing. http://staart.nmr.io/register
In addition, I look forward to an active example with Facebook / Google. Thanks for the project!

**Comment by mulikaminker** [comment]
Sorry. now i see that the errors from register validation shows only in the console.

**Comment by nickredmark** [comment]
True story! That's a bug, it should show the error message in the form. I'll update the example when I'm home.

**Comment by nickredmark** [comment]
Thanks for reporting

**Comment by nickredmark** [comment]
Error messages are now appearing. And created two new issues for facebook and google: https://github.com/nmaro/staart/issues/4 https://github.com/nmaro/staart/issues/3
