### ISSUE TITLE
Example page is not working

### ISSUE THREAD

**Issue by bennygenel** [nmaro/staart#21]
Live example page https://staart.nmr.io/ is giving a `502 Bad Gateway` error.

Just giving you a heads up.

**Comment by nickredmark** [comment]
Thanks! I'll fix it when I find the time and report it here.

**Comment by RobertB4** [comment]
Still not fixed, is this project being maintained?

**Comment by nickredmark** [comment]
I just released Ooth 2 and Staart 3. Sample page is back online.
