### ISSUE TITLE
Where are the client side actions?

### ISSUE THREAD

**Issue by Tzikas** [nmaro/staart#24]
I'm trying to use your server side code with an expo (react-native) client side, but I'm little confused about how I would do that, since there are no api endpoints due to Apollo I'm guessing, and also I don't see any client side POST actions that I can mimic.  

I suppose it has something to do with ```new OothClient({``` ooth?  Are there any RN boilerplates or tutorials using ooth that you know of?

**Comment by nickredmark** [comment]
I tried to exaplain this in the documentation, but let me know if something remains unclear:

General ooth-client stuff:
https://nmaro.github.io/ooth/#ooth-client

ooth-local strategy
https://nmaro.github.io/ooth/#client-1

ooth-facebook strategy
https://nmaro.github.io/ooth/#client-2

**Comment by nickredmark** [comment]
By the way ooth exposes a REST API endpoint that is structured as follows:

`POST <ooth>/<strategy>/<method>`

and in the body would contain a json of the needed variables. For example

`POST /auth/local/register` with body

`{
  "email": "xxx",
  "password": "xxx"
}
`

**Comment by nickredmark** [comment]
And no, I don't know of any react native library using ooth. I think there is just the need for someone to take the time and share a reference implementation.

In the [slack channel](https://join.slack.com/t/ooth/shared_invite/enQtMjQ3MDE2ODA2NjE0LTE1NGNmN2YzZTdiMWNjODExZmNjYzg3ZGJjZmVmZmI2YjVhOWYzZDQ1NWI4Y2JiNzNlMmI2Y2U5ZWFhODIzMWQ) there is a channel called #mobile for people like you.
