### ISSUE TITLE
Doesn't start with node 8.2.1 (Windows)

### ISSUE THREAD

**Issue by trickidicki** [nmaro/staart#7]
G:\work\node\staart\examples\staart>yarn
yarn install v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 22.90s.

G:\work\node\staart\examples\staart>yarn run dev
yarn run v0.15.1
$ node --harmony-async-await index.js
node: bad option: --harmony-async-await
error Command failed with exit code 9.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.

I suspect related to [this](https://github.com/zpnk/stage-ci/issues/23)

**Comment by nickredmark** [comment]
True story. At the moment I'm using node 7.5 because npm 5 randomly removes linked packages: https://github.com/npm/npm/issues/17533
I haven't tried it, but if you remove the `--harmony-async-await` option from the package.json it should work.

**Comment by trickidicki** [comment]
Yes indeed, that was the solution.

**Comment by nickredmark** [comment]
I'll close this. Will update to 8 as soon as linked packages problem is fixed, see https://github.com/nmaro/staart/issues/11
