### ISSUE TITLE
Associate new login method

### ISSUE THREAD

**Issue by adcooley** [nmaro/staart#9]
Would love to have examples included for associating a new login method with an existing account.

Basically, on the Account page while logged in, the Facebook component would have "Link with Facebook", and same for Google, etc

**Comment by nickredmark** [comment]
Sounds good

**Comment by nickredmark** [comment]
This needs an extension of ooth, working on that.

**Comment by nickredmark** [comment]
The staart accounts page now allows one to connect username/password, facebook and google strategies while logged in.

Live example is http://staart.nmr.io/account.

Relevant components are:

https://github.com/nmaro/staart/blob/master/packages/staart/src/components/account-facebook.js
https://github.com/nmaro/staart/blob/master/packages/staart/src/components/account-google.js
https://github.com/nmaro/staart/blob/master/packages/staart/src/components/account-local.js

**Comment by adcooley** [comment]
Awesome, thank you!
